### ISSUE TITLE
maven-repo直接404

### ISSUE THREAD

**Issue by notfresh** [michaelliao/how-to-become-rich#6]
https://michaelliao.github.io/how-to-become-rich/maven-repo/ 这个网址目前在github-io上网址不可用了

也许是github.io 改版了，只有一页了吧，后缀网址可能不支持了。

**Comment by michaelliao** [comment]
大部分web服务器不支持浏览目录，但是不影响你访问文件：

https://michaelliao.github.io/how-to-become-rich/maven-repo/com/itranswarp/rich/how-to-become-rich/1.0.0/how-to-become-rich-1.0.0.jar
